# Generated by Django 4.1.7 on 2023-02-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosNF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestador', models.CharField(max_length=50)),
                ('convenio', models.CharField(max_length=50)),
                ('protocolo', models.CharField(max_length=12)),
                ('remessa', models.CharField(max_length=20)),
                ('classificacao', models.CharField(max_length=50)),
                ('rps', models.CharField(max_length=20)),
                ('nfe', models.CharField(max_length=20)),
                ('emissao', models.CharField(max_length=20)),
                ('vencimento', models.CharField(max_length=20)),
            ],
        ),
    ]
